runtime: python27
api_version: 1
threadsafe: yes

handlers:
#- url: /favicon\.ico
#  static_files: favicon.ico
#  upload: favicon\.ico

#new handlers should go ABOVE the catch all url (.*)
- url: /i
  static_dir: static 

- url: /p/(.*)
  script: main.app
  login: required

- url: .*
  script: main.app

- url: /createbracket
  script: createbracket.app
  login: admin


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"